In [1]:
import pandas as pd
dataset=pd.read_csv("insurance.csv")
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [2]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,True,False,True,False,False
1334,18,31.920,0,2205.98080,False,False,False,False,False
1335,18,36.850,0,1629.83350,False,False,False,True,False
1336,21,25.800,0,2007.94500,False,False,False,False,True
1337,61,29.070,0,29141.36030,False,True,True,False,False

In [3]:
x=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']] 
y=dataset['charges']

In [4]:
x

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [5]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [7]:
from sklearn.ensemble import AdaBoostRegressor

In [8]:

regr = AdaBoostRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

regr.fit(x_train, y_train)

AdaBoostRegressor(learning_rate=0.1, n_estimators=100, random_state=42)

In [10]:
y_pred = regr.predict(x_test)
y_pred

array([13292.08324615,  7575.1884628 , 26075.1728274 , 13292.08324615,
       36608.0916865 ,  8412.96602096,  5614.92722432, 15738.4867458 ,
        7208.72004125, 14029.68901649, 19128.93206515,  9849.60689611,
        8450.43950789, 46205.4752629 , 46205.4752629 , 46205.4752629 ,
       13976.44443183, 46205.4752629 , 13251.21735282, 25814.51982   ,
       10174.52399542, 11590.41533128,  5614.92722432,  6582.60334119,
       14118.2054587 , 14506.90076099, 15738.4867458 ,  9849.60689611,
       13453.15837072,  5499.25048639,  9870.42594114, 14524.71855245,
        6582.60334119,  9870.42594114,  8450.43950789, 12628.34722126,
        8412.96602096, 10507.89122533, 25487.3848442 , 44774.92858305,
        8873.77797835,  8412.96602096, 15202.62872693, 15738.4867458 ,
        9849.60689611, 17796.07419495,  9849.60689611,  9870.42594114,
       45532.13014838,  9677.52941676, 15738.4867458 ,  7661.37656309,
        8412.96602096,  5499.25048639, 14524.71855245, 14118.2054587 ,
        7208.72004125, 44403.98078414, 14524.71855245, 14478.25137796,
       15738.4867458 ,  9677.52941676, 18206.88498104,  9870.42594114,
       14178.10644962,  8450.43950789, 19227.6616454 , 14472.99881228,
        8450.43950789,  6582.60334119,  8450.43950789, 13292.08324615,
       13601.40260483,  9849.60689611, 13251.21735282,  7575.1884628 ,
        9849.60689611, 14524.71855245,  9849.60689611, 13292.08324615,
        6582.60334119, 26075.1728274 ,  9849.60689611, 36608.0916865 ,
       36608.0916865 , 46205.4752629 ,  9849.60689611, 14524.71855245,
       11590.41533128, 14965.24299902, 18477.03944187, 25487.3848442 ,
       26075.1728274 ,  9849.60689611, 44774.92858305,  9849.60689611,
       19407.17375586,  6582.60334119, 19128.93206515,  9870.42594114,
        8450.43950789,  5614.92722432,  7294.22369647, 15315.50511425,
       15738.4867458 ,  7661.37656309, 13292.08324615, 25467.55169045,
        5499.25048639, 25487.3848442 ,  5614.92722432,  8412.96602096,
       15202.62872693, 44774.92858305, 13976.44443183,  8412.96602096,
       15738.4867458 , 25814.51982   ,  9849.60689611,  8450.43950789,
        8450.43950789,  9849.60689611, 14343.47029094,  7208.72004125,
        9870.42594114,  9849.60689611, 10507.89122533, 13976.44443183,
       15738.4867458 ,  7034.99375392,  7575.1884628 ,  9849.60689611,
        9849.60689611, 12628.34722126,  7575.1884628 , 17796.07419495,
        7575.1884628 , 38128.88502851, 45553.8249909 , 44774.92858305,
        7575.1884628 , 13601.40260483,  7208.72004125, 14343.47029094,
        7208.72004125, 25684.2390588 ,  9849.60689611,  7208.72004125,
       14118.2054587 ,  8450.43950789, 46205.4752629 ,  7208.72004125,
        5499.25048639, 44774.92858305,  8412.96602096,  7575.1884628 ,
       15738.4867458 , 13453.15837072, 36608.0916865 , 44774.92858305,
       15315.50511425,  7699.2112369 , 18206.88498104,  7208.72004125,
        9849.60689611,  9849.60689611, 46205.4752629 , 46205.4752629 ,
       45553.8249909 ,  7208.72004125, 13976.44443183,  8450.43950789,
        7294.22369647,  8450.43950789,  6582.60334119, 25487.3848442 ,
       19369.38543646, 15738.4867458 , 18806.29279324, 14506.90076099,
       26075.1728274 ,  8450.43950789, 13292.08324615,  8450.43950789,
        9870.42594114,  7208.72004125,  8450.43950789,  7208.72004125,
       13453.15837072, 14524.71855245,  9849.60689611,  5499.25048639,
        6582.60334119, 44403.98078414, 15738.4867458 , 13601.40260483,
        7699.2112369 , 15020.50572542,  5499.25048639, 13601.40260483,
        7208.72004125, 26075.1728274 ,  9677.52941676,  8806.50497411,
       19369.38543646, 19128.93206515, 13601.40260483,  9849.60689611,
       13453.15837072,  8450.43950789, 15738.4867458 , 15020.50572542,
       13292.08324615, 19407.17375586,  9870.42594114,  7208.72004125,
        8450.43950789, 18477.03944187, 15738.4867458 ,  8450.43950789,
        6582.60334119, 12628.34722126,  9677.52941676, 45532.13014838,
        6582.60334119, 43375.93568226,  5614.92722432,  5614.92722432,
       14118.2054587 , 13976.44443183,  6582.60334119, 13453.15837072,
        9870.42594114, 25814.51982   , 14135.41974736, 13601.40260483,
        9849.60689611,  7575.1884628 , 44967.31127853,  6582.60334119,
       15738.4867458 , 43375.93568226,  7208.72004125,  8450.43950789,
        5614.92722432,  7208.72004125,  9849.60689611,  8450.43950789,
       14343.47029094,  5614.92722432,  6582.60334119,  9849.60689611,
        7208.72004125, 14506.90076099,  7699.2112369 ,  8450.43950789,
       15738.4867458 ,  8450.43950789, 13453.15837072,  9849.60689611,
        9849.60689611, 15738.4867458 , 19407.17375586, 46205.4752629 ,
       14524.71855245,  8450.43950789, 46205.4752629 , 14118.2054587 ])

In [11]:
from sklearn.metrics import r2_score

y_pred = regr.predict(x_test)

print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.8201817117572223