In [4]:
import pandas as pd
dataset=pd.read_csv("insurance.csv")
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,True,False,True,False,False
1334,18,31.920,0,2205.98080,False,False,False,False,False
1335,18,36.850,0,1629.83350,False,False,False,True,False
1336,21,25.800,0,2007.94500,False,False,False,False,True
1337,61,29.070,0,29141.36030,False,True,True,False,False

In [6]:
x=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']] 
y=dataset['charges']

In [4]:
x

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [5]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [8]:
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score

reg = LGBMRegressor(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=-1,
    random_state=42,
    verbosity=-1
)

reg.fit(x_train, y_train)

y_pred = reg.predict(x_test)

print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.8750571659487228

In [8]:
%pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.7.0-py3-none-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: narwhals>=1.15 in C:\Users\aashi\anaconda3\Lib\site-packages (from lightgbm) (2.23.0)
Requirement already satisfied: numpy>=1.21.3 in C:\Users\aashi\anaconda3\Lib\site-packages (from lightgbm) (2.4.6)
Requirement already satisfied: scipy in C:\Users\aashi\anaconda3\Lib\site-packages (from lightgbm) (1.18.0)
Downloading lightgbm-4.7.0-py3-none-win_amd64.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   -------------------------------------- - 1.3/1.4 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 6.0 MB/s  0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.7.0
Note: you may need to restart the kernel to use updated packages.

In [11]:
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score

reg = LGBMRegressor(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=-1,
    random_state=42,
    verbosity=-1
)

reg.fit(x_train, y_train)

y_pred = reg.predict(x_test)
print(y_pred)

[10954.95862655  5790.60480194 27093.29147371  8437.11164095
 33915.07824516  6858.32481678  1959.34082414 14125.23914276
  4708.06127027 10150.72921652 19033.77489569  9187.63384132
  6626.39379507 45457.65113395 48093.11807518 45372.83129227
  9157.55476401 43941.69932147 10836.78092566 25196.48507348
  8581.92723815 10097.9714669   2701.88490869  3500.19452422
 12219.48169953 13362.24137985 15543.65510604  7257.99011349
 11045.8759296   3012.63092528  8138.99204321 12691.10852347
  2014.58407029  5156.75882044  4303.52103468  8622.53488034
  4603.57501626  9198.46057384 23593.41652657 39665.63502957
  9663.51904415  3643.4958542  13829.4440037  13859.14223245
  7535.34381211 14678.92028779 10340.38623201 10869.4583881
 42361.40215696  7866.99898805 15601.60303694  3693.25753136
  7423.63267075  1276.34198952 10336.83493811 10058.02814681
  2652.82727312 38990.13613719 12298.20710814 13066.55912739
 13982.67183109  4355.86921604 18890.76609858  9534.07545441
 10851.92978614  6337.4625685  18329.65801506 13452.17289054
  6650.59332834  3624.21987916  6375.97415126 10038.62630912
 11008.85735988  9180.3714837   9878.86573754  5790.60480194
  6466.25869352 13565.92848494  8541.88763003  8617.16380266
  3061.43261901 27516.85318868  8394.57779397 38349.40908511
 38362.99003618 41179.73641363  4098.33523833 13047.85669177
 10091.75636275 16527.915546   19084.93969876 24768.44131772
 25097.41068813  6416.07435376 41863.25034643  8237.06108071
 20741.48142543  3684.69848462 17323.44867585  8818.4934871
  4301.18946118  2153.49387033  7127.01897778 15159.8981241
 13560.35561109  4542.6456049  10396.64969569 22187.0640873
  1899.47372707 23682.45117115  2411.19118453  4611.45377504
 12077.74118796 39628.90545065  9227.95377081  5042.11424531
 12783.12254039 25605.28840762  7828.42185019  5901.24886314
  6288.0340734   8604.35993852 12279.35336756  4959.45447159
  7725.31186066  9163.60584495 11588.81046715  9161.53255807
 16273.66036538  4689.5223876   3496.26227051  7132.34098681
  8881.00059253  9860.82403028  7181.04420317 20325.39296722
  4443.69954414 31827.87546947 45898.14165711 39476.73425137
  5242.79505342 10789.75583327  4467.2746725  13747.57868121
  2654.3868432  24163.28569457  6044.44051594  3316.41169132
 13256.02019692  5452.87465916 47094.40285818  6123.49368792
  3405.31113717 38483.23450068  7132.98766395  4287.61521336
 13735.00999105 10240.01854613 35064.28717037 38643.20565309
 13585.97956963  3936.36991323 17594.22555288  5231.44954043
  7187.29184214  7423.84258219 47994.09670951 44751.02026447
 41481.67986174  4993.76180513  9365.68470341  7054.17114024
  7082.71257902  4703.38575972  2918.96772262 23380.14841289
 17825.01837458 12905.16064273 16060.01404128 11262.61720514
 27074.07192654  3142.68013263  9299.19186256  6756.68719007
  6394.1200358   6673.28666293  6605.18305607  4427.74154861
  8598.7947582  12925.34112373  4197.20562935  2911.29038125
  3228.53823777 42970.31253538 13225.19795947  9835.90207653
  5622.89954687 12392.08061074  2117.44549951 12433.03495597
  5772.37254387 26685.51924857  4759.22349371  5576.68517407
 17995.61344207 18778.8933908  10467.36170539  5564.11909437
  9592.17526049  4690.36562718 13952.53895155 12047.57576743
  7647.3973288  18935.47901995  9521.60267018  4427.74154861
  5698.10890461 15331.72865615 14267.50767029  5140.03288662
  3058.6052074   8645.87769323  7112.92167823 45370.85580892
  2090.74341604 36257.36149707  1643.92365423  3745.85764158
  8457.51086331 10378.37756989  2771.44585818  9241.78107822
  9976.37965477 26379.64462771 11289.89343013 10758.11933682
  7185.6606032   7342.7745873  45114.34185234  4202.07291239
 13655.48139512 40121.25034458  3196.29951319  6206.35970283
   851.07841721  2824.00227066  6984.89285006  4317.38527261
 12419.75690189  1597.13561693  3690.20837841  7587.07257021
  3251.5866846  11385.54189566  4652.20860685  5668.25075323
 12606.92938913  5827.10515543  9113.92825166  5458.68432146
  6427.55515464 14178.11420421 20836.66554398 47164.69720925
 12200.08926067  6160.59480069 46785.36439973  9366.46614783]

In [12]:
print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.8750571659487228