In [1]:
import pandas as pd
dataset=pd.read_csv("insurance.csv")
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [2]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [3]:
dataset

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,True,False,True,False,False
1334,18,31.920,0,2205.98080,False,False,False,False,False
1335,18,36.850,0,1629.83350,False,False,False,True,False
1336,21,25.800,0,2007.94500,False,False,False,False,True
1337,61,29.070,0,29141.36030,False,True,True,False,False

In [4]:
x=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']] 
y=dataset['charges']

In [5]:
x

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [6]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [8]:
from sklearn import ensemble
from sklearn.metrics import mean_squared_error
reg = ensemble.GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    min_samples_split=5,
    min_samples_leaf=2,
    subsample=0.8,
    loss='squared_error',
    random_state=42
)
reg.fit(x_train, y_train)

GradientBoostingRegressor(learning_rate=0.05, min_samples_leaf=2,
                          min_samples_split=5, n_estimators=200,
                          random_state=42, subsample=0.8)

In [9]:
y_pred = reg.predict(x_test)
y_pred

array([10467.43450681,  5962.19602489, 29652.37786436,  9763.01220015,
       34135.61753052,  6020.12084806,  3561.97889443, 14550.73677105,
        4138.69765651, 10292.05447744, 19252.78718781,  9141.97327224,
        5892.43360197, 45348.31112203, 48076.86716933, 46117.60842001,
       10461.21916893, 45790.75944907,  9393.60528826, 24362.02120241,
        6792.64145518,  9647.54892621,  2592.4657633 ,  2687.452765  ,
       11347.14199985, 12666.32873404, 14172.47592764,  6536.83792904,
       10797.63000001,  2782.72105109,  7628.95444243, 12243.17183714,
        2956.87504375,  6061.92399992,  5103.74819565,  9431.94662121,
        3901.44995202,  9237.04608776, 25991.29480681, 40291.41547461,
        7264.13247765,  3686.42383746, 13833.33032006, 14692.72182264,
        7892.28812926, 15255.4568624 ,  6981.81015244,  7626.65118248,
       43486.63732479,  6520.07528323, 15059.06393793,  3386.41839704,
        6693.352103  ,  1419.36863224, 11818.11944312, 11022.1173199 ,
        4342.89627727, 39625.82874049, 12794.6271959 , 12388.03198868,
       14596.49790396,  5692.57216149, 18334.533424  ,  9632.50012105,
       11216.86431158,  5723.62627461, 18409.10695566, 12286.50497551,
        7045.23469615,  2538.57933209,  6901.29000332, 10404.43012513,
       10880.08293002,  7583.31268016, 10292.08402552,  5886.99753488,
        6158.12750439, 12851.92473765,  7104.64476497, 10130.41717815,
        3197.42666132, 27387.81616667,  9419.93138349, 39336.87028354,
       38888.45045679, 41727.17032206,  5990.43409978, 12342.65888323,
        9588.34189234, 15187.5894091 , 23285.58225328, 28102.1596023 ,
       25765.89238185,  6783.23322476, 41892.00610003,  7519.80822939,
       20978.48797423,  3893.56834318, 18107.16199311,  7472.27403464,
        5498.8575849 ,  2447.21138852,  5892.31787636, 14538.48395718,
       13369.8474201 ,  3322.41305875,  9457.52436832, 22115.53680298,
        1452.34372893, 24726.59804585,  2462.40843398,  4189.75659946,
       13648.74244576, 39652.60790987, 10583.75879744,  4493.19839847,
       13073.28013606, 23940.19566911,  7616.35582402,  5847.70545102,
        6967.87263962,  7597.04424487, 12546.6631765 ,  4221.94343964,
        6417.95036676,  8154.16019456,  9747.98784362, 10395.74670366,
       14131.19371398,  5087.99915238,  4055.11372146,  7253.90986492,
        8248.87789653, 11560.28420635,  6642.51455174, 17023.77076275,
        4977.99164873, 37294.27534692, 45435.00011919, 39048.80542282,
        6203.77616494, 10361.31558395,  4187.03020708, 13278.70816998,
        3857.81364993, 24349.89785693,  7235.94999969,  4055.11372146,
       12075.76346958,  6433.00356867, 49755.92223078,  5175.25432491,
        3078.59428534, 39567.94951553,  6487.7624084 ,  5329.23888263,
       14038.19336133,  9807.41925352, 34839.87932408, 39717.26381796,
       13611.0166053 ,  3639.98664255, 19899.2269448 ,  5813.91368941,
        6646.9931359 ,  7928.38280406, 48010.63175068, 43729.52088047,
       41612.65781858,  4470.4724327 ,  9721.83002319,  7205.42548762,
        5840.58436568,  5069.9736997 ,  3304.5568169 , 24512.76217764,
       17054.69736258, 14243.32173883, 16349.14095874, 11992.50119125,
       27414.22739376,  3312.70025399,  8760.24782441,  6787.5379622 ,
        7119.56922041,  5047.23859415,  6248.26039979,  4725.55180622,
        9222.00300312, 13075.67577477,  6408.2328906 ,  2791.85486099,
        3844.99412084, 42390.69187507, 15336.61766208, 10530.65705393,
        4799.99309609, 12807.21086383,  2260.77007119, 11059.94371076,
        4216.04959268, 26653.65425984,  5578.76821537,  5421.28534954,
       19401.16294337, 18530.59922583, 10184.50995681,  4967.73113511,
        9945.43523881,  5024.80327969, 13115.80746291, 12289.6650324 ,
        8767.55435763, 18673.00823613,  9571.86451715,  4786.9026933 ,
        6488.38233517, 15756.94037485, 14885.47685654,  6613.80403636,
        3540.99385504,  8684.56569303,  6714.24324046, 45409.77562864,
        2414.59841263, 37355.25225137,  1771.95938951,  3042.06707056,
       10512.46942561, 13463.06018017,  2868.56663442,  9923.12564724,
        7957.5054515 , 23946.96329828, 11073.78944493, 10618.72302423,
        6064.9037614 ,  6174.4088528 , 44038.29474229,  2605.88030109,
       14014.23811773, 39963.12415276,  4588.43478653,  5673.90996025,
        1577.76347575,  3708.16075953,  7152.90963222,  5063.98575476,
       14687.70782235,  1606.35856136,  4060.93258837,  7374.55220341,
        4427.96884312, 11473.58521829,  4348.56019708,  5630.74322317,
       13073.28013606,  5070.54931708, 10015.05099421,  6471.38380139,
        7257.43848672, 13772.12605136, 19939.68884279, 45662.18608864,
       13438.61794104,  6823.60352718, 47714.12567227, 10648.8148777 ])

In [10]:
from sklearn.metrics import r2_score

y_pred = reg.predict(x_test)

print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.8743742637155224