In [1]:
import pandas as pd
dataset=pd.read_csv("50_Startups_dataset.csv")

In [2]:
dataset

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,State,Profit
0,0,165349.30,136897.90,471784.20,New York,192261.93
1,1,162597.80,151377.69,443898.63,California,191792.16
2,2,153441.61,101145.65,407934.64,Florida,191050.49
3,3,144372.51,118671.95,383199.72,New York,182902.09
4,4,142107.44,91391.87,366168.52,Florida,166188.04
5,5,131877.00,99814.81,362861.46,New York,156991.22
6,6,134615.56,147198.97,127716.92,California,156122.61
7,7,130298.23,145530.16,323876.78,Florida,155752.70
8,8,120542.62,148719.05,311613.39,New York,152211.87
9,9,123334.98,108679.27,304981.72,California,149760.06
10,10,101913.18,110594.21,229161.05,Florida,146122.05
11,11,100672.06,91790.71,249744.65,California,144259.50
12,12,93863.85,127320.48,249839.54,Florida,141585.62
13,13,91992.49,135495.17,252665.03,California,134307.45
14,14,119943.34,156547.52,256513.02,Florida,132602.75
15,15,114523.71,122616.94,261776.33,New York,129917.14
16,16,78013.21,121597.65,264346.16,California,126993.03
17,17,94657.26,145077.68,282574.41,New York,125370.47
18,18,91749.26,114175.89,294919.67,Florida,124267.00
19,19,86419.80,153514.21,0.10,New York,122776.96
20,20,76253.96,113867.40,298664.57,California,118474.13
21,21,78389.57,153773.53,299737.39,New York,111313.12
22,22,73994.66,122782.85,303319.36,Florida,110352.35
23,23,67532.63,105751.13,304768.83,Florida,108734.09
24,24,77044.11,99281.44,140574.91,New York,108552.14
25,25,64664.81,139553.26,137962.72,California,107404.44
26,26,75328.97,144136.08,134050.17,Florida,105733.64
27,27,72107.70,127864.65,353183.91,New York,105008.41
28,28,66051.62,182645.66,118148.30,Florida,103282.48
29,29,65605.58,153032.16,107138.48,New York,101004.74
30,30,61994.58,115641.38,91131.34,Florida,99937.69
31,31,61136.48,152702.02,88218.33,New York,97483.66
32,32,63408.96,129219.71,46085.35,California,97427.94
33,33,55494.05,103057.59,214634.91,Florida,96779.02
34,34,46426.17,157694.02,210797.77,California,96712.90
35,35,46014.12,85047.54,205517.74,New York,96479.61
36,36,28663.86,127056.31,201126.92,Florida,90708.29
37,37,44070.05,51283.24,197029.52,California,89949.24
38,38,20229.69,65948.03,185265.20,New York,81229.16
39,39,38558.61,82982.19,174999.40,California,81005.86
40,40,28754.43,118546.15,172795.77,California,78240.01
41,41,27893.02,84710.87,164470.81,Florida,77798.93
42,42,23641.03,96189.73,148001.21,California,71498.59
43,43,15505.83,127382.40,35534.27,New York,69759.08
44,44,22177.84,154806.24,28334.82,California,65200.43
45,45,1000.33,124153.14,1904.03,New York,64926.18
46,46,1315.56,115816.31,297114.56,Florida,49490.85
47,47,0.10,135427.02,0.10,California,42559.83
48,48,542.15,51743.25,0.10,New York,35673.51
49,49,0.10,116983.90,45173.16,California,14681.50

In [2]:
dataset = pd.get_dummies(dataset, columns=["State"], dtype=int)
dataset

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,Profit,State_California,State_Florida,State_New York
0,0,165349.30,136897.90,471784.20,192261.93,0,0,1
1,1,162597.80,151377.69,443898.63,191792.16,1,0,0
2,2,153441.61,101145.65,407934.64,191050.49,0,1,0
3,3,144372.51,118671.95,383199.72,182902.09,0,0,1
4,4,142107.44,91391.87,366168.52,166188.04,0,1,0
5,5,131877.00,99814.81,362861.46,156991.22,0,0,1
6,6,134615.56,147198.97,127716.92,156122.61,1,0,0
7,7,130298.23,145530.16,323876.78,155752.70,0,1,0
8,8,120542.62,148719.05,311613.39,152211.87,0,0,1
9,9,123334.98,108679.27,304981.72,149760.06,1,0,0
10,10,101913.18,110594.21,229161.05,146122.05,0,1,0
11,11,100672.06,91790.71,249744.65,144259.50,1,0,0
12,12,93863.85,127320.48,249839.54,141585.62,0,1,0
13,13,91992.49,135495.17,252665.03,134307.45,1,0,0
14,14,119943.34,156547.52,256513.02,132602.75,0,1,0
15,15,114523.71,122616.94,261776.33,129917.14,0,0,1
16,16,78013.21,121597.65,264346.16,126993.03,1,0,0
17,17,94657.26,145077.68,282574.41,125370.47,0,0,1
18,18,91749.26,114175.89,294919.67,124267.00,0,1,0
19,19,86419.80,153514.21,0.10,122776.96,0,0,1
20,20,76253.96,113867.40,298664.57,118474.13,1,0,0
21,21,78389.57,153773.53,299737.39,111313.12,0,0,1
22,22,73994.66,122782.85,303319.36,110352.35,0,1,0
23,23,67532.63,105751.13,304768.83,108734.09,0,1,0
24,24,77044.11,99281.44,140574.91,108552.14,0,0,1
25,25,64664.81,139553.26,137962.72,107404.44,1,0,0
26,26,75328.97,144136.08,134050.17,105733.64,0,1,0
27,27,72107.70,127864.65,353183.91,105008.41,0,0,1
28,28,66051.62,182645.66,118148.30,103282.48,0,1,0
29,29,65605.58,153032.16,107138.48,101004.74,0,0,1
30,30,61994.58,115641.38,91131.34,99937.69,0,1,0
31,31,61136.48,152702.02,88218.33,97483.66,0,0,1
32,32,63408.96,129219.71,46085.35,97427.94,1,0,0
33,33,55494.05,103057.59,214634.91,96779.02,0,1,0
34,34,46426.17,157694.02,210797.77,96712.90,1,0,0
35,35,46014.12,85047.54,205517.74,96479.61,0,0,1
36,36,28663.86,127056.31,201126.92,90708.29,0,1,0
37,37,44070.05,51283.24,197029.52,89949.24,1,0,0
38,38,20229.69,65948.03,185265.20,81229.16,0,0,1
39,39,38558.61,82982.19,174999.40,81005.86,1,0,0
40,40,28754.43,118546.15,172795.77,78240.01,1,0,0
41,41,27893.02,84710.87,164470.81,77798.93,0,1,0
42,42,23641.03,96189.73,148001.21,71498.59,1,0,0
43,43,15505.83,127382.40,35534.27,69759.08,0,0,1
44,44,22177.84,154806.24,28334.82,65200.43,1,0,0
45,45,1000.33,124153.14,1904.03,64926.18,0,0,1
46,46,1315.56,115816.31,297114.56,49490.85,0,1,0
47,47,0.10,135427.02,0.10,42559.83,1,0,0
48,48,542.15,51743.25,0.10,35673.51,0,0,1
49,49,0.10,116983.90,45173.16,14681.50,1,0,0

In [3]:
x= dataset.drop(columns=["Profit"])
y = dataset["Profit"]

In [4]:
dataset = dataset.drop(columns=["State_California"])
dataset

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,0,165349.30,136897.90,471784.20,192261.93,0,1
1,1,162597.80,151377.69,443898.63,191792.16,0,0
2,2,153441.61,101145.65,407934.64,191050.49,1,0
3,3,144372.51,118671.95,383199.72,182902.09,0,1
4,4,142107.44,91391.87,366168.52,166188.04,1,0
5,5,131877.00,99814.81,362861.46,156991.22,0,1
6,6,134615.56,147198.97,127716.92,156122.61,0,0
7,7,130298.23,145530.16,323876.78,155752.70,1,0
8,8,120542.62,148719.05,311613.39,152211.87,0,1
9,9,123334.98,108679.27,304981.72,149760.06,0,0
10,10,101913.18,110594.21,229161.05,146122.05,1,0
11,11,100672.06,91790.71,249744.65,144259.50,0,0
12,12,93863.85,127320.48,249839.54,141585.62,1,0
13,13,91992.49,135495.17,252665.03,134307.45,0,0
14,14,119943.34,156547.52,256513.02,132602.75,1,0
15,15,114523.71,122616.94,261776.33,129917.14,0,1
16,16,78013.21,121597.65,264346.16,126993.03,0,0
17,17,94657.26,145077.68,282574.41,125370.47,0,1
18,18,91749.26,114175.89,294919.67,124267.00,1,0
19,19,86419.80,153514.21,0.10,122776.96,0,1
20,20,76253.96,113867.40,298664.57,118474.13,0,0
21,21,78389.57,153773.53,299737.39,111313.12,0,1
22,22,73994.66,122782.85,303319.36,110352.35,1,0
23,23,67532.63,105751.13,304768.83,108734.09,1,0
24,24,77044.11,99281.44,140574.91,108552.14,0,1
25,25,64664.81,139553.26,137962.72,107404.44,0,0
26,26,75328.97,144136.08,134050.17,105733.64,1,0
27,27,72107.70,127864.65,353183.91,105008.41,0,1
28,28,66051.62,182645.66,118148.30,103282.48,1,0
29,29,65605.58,153032.16,107138.48,101004.74,0,1
30,30,61994.58,115641.38,91131.34,99937.69,1,0
31,31,61136.48,152702.02,88218.33,97483.66,0,1
32,32,63408.96,129219.71,46085.35,97427.94,0,0
33,33,55494.05,103057.59,214634.91,96779.02,1,0
34,34,46426.17,157694.02,210797.77,96712.90,0,0
35,35,46014.12,85047.54,205517.74,96479.61,0,1
36,36,28663.86,127056.31,201126.92,90708.29,1,0
37,37,44070.05,51283.24,197029.52,89949.24,0,0
38,38,20229.69,65948.03,185265.20,81229.16,0,1
39,39,38558.61,82982.19,174999.40,81005.86,0,0
40,40,28754.43,118546.15,172795.77,78240.01,0,0
41,41,27893.02,84710.87,164470.81,77798.93,1,0
42,42,23641.03,96189.73,148001.21,71498.59,0,0
43,43,15505.83,127382.40,35534.27,69759.08,0,1
44,44,22177.84,154806.24,28334.82,65200.43,0,0
45,45,1000.33,124153.14,1904.03,64926.18,0,1
46,46,1315.56,115816.31,297114.56,49490.85,1,0
47,47,0.10,135427.02,0.10,42559.83,0,0
48,48,542.15,51743.25,0.10,35673.51,0,1
49,49,0.10,116983.90,45173.16,14681.50,0,0

In [5]:
x= dataset.drop(columns=["Profit"])
y = dataset["Profit"]

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [19]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(x_train, y_train)

DecisionTreeRegressor()

In [20]:
y_pred = regressor.predict(x_test)
y_pred

array([141585.62,  78240.01,  97483.66,  49490.85, 126993.03,  42559.83,
       105008.41, 108734.09, 101004.74, 129917.14])

In [21]:
from sklearn.metrics import r2_score

y_pred = regressor.predict(x_test)

print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.9480092391194808

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [16]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(x_train, y_train)

DecisionTreeRegressor()

In [17]:
y_pred = regressor.predict(x_test)
y_pred

array([141585.62,  81229.16, 101004.74,  49490.85, 129917.14,  49490.85,
       103282.48, 110352.35,  97483.66, 129917.14])

In [18]:
from sklearn.metrics import r2_score

y_pred = regressor.predict(x_test)

print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.929650539381207

In [22]:
from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor(
    random_state=42,
    max_features=None,
    criterion='squared_error',
    splitter='best'
)

regressor.fit(x_train, y_train)

DecisionTreeRegressor(random_state=42)

In [23]:
y_pred = regressor.predict(x_test)
y_pred

array([141585.62,  81229.16,  97483.66,  49490.85, 124267.  ,  49490.85,
       103282.48, 111313.12, 101004.74, 132602.75])

In [24]:
from sklearn.metrics import r2_score

y_pred = regressor.predict(x_test)

print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.9234302903427023

In [7]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(
    n_estimators=1000,
    random_state=42,
    max_features='log2',
    criterion='squared_error'
)

regressor.fit(x_train, y_train)

RandomForestRegressor(max_features='log2', n_estimators=1000, random_state=42)

In [8]:
y_pred = regressor.predict(x_test)
y_pred

array([136930.45126,  83797.04193,  96479.19422,  55478.25662,
       128950.68494,  50379.26164, 108137.159  , 104360.76829,
        86940.89212, 114567.1593 ])

In [9]:
from sklearn.metrics import r2_score

y_pred = regressor.predict(x_test)

print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.9336382497392763

In [10]:
import pandas as pd
from itertools import product
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

random_states = [0, 42]
max_features_values = [1.0, "sqrt"]
criteria = ['squared_error', 'absolute_error']
n_estimators_values = [100, 1000]

results = []

for rs, mf, cr, ne in product(
    random_states,
    max_features_values,
    criteria,
    n_estimators_values
):
    regressor = RandomForestRegressor(
        n_estimators=ne,
        random_state=rs,
        max_features=mf,
        criterion=cr
    )

    regressor.fit(x_train, y_train)
    y_pred = regressor.predict(x_test)

    results.append({
        'S.No': len(results) + 1,
        'random_state': rs,
        'max_features': mf,
        'criterion': cr,
        'n_estimators': ne,
        'R2 Score': round(r2_score(y_test, y_pred), 4)
    })

df = pd.DataFrame(results)

display(df)

    S.No  random_state max_features       criterion  n_estimators  R2 Score
0      1             0          1.0   squared_error           100    0.9841
1      2             0          1.0   squared_error          1000    0.9746
2      3             0          1.0  absolute_error           100    0.9768
3      4             0          1.0  absolute_error          1000    0.9749
4      5             0         sqrt   squared_error           100    0.9060
5      6             0         sqrt   squared_error          1000    0.9344
6      7             0         sqrt  absolute_error           100    0.9116
7      8             0         sqrt  absolute_error          1000    0.9319
8      9            42          1.0   squared_error           100    0.9764
9     10            42          1.0   squared_error          1000    0.9750
10    11            42          1.0  absolute_error           100    0.9732
11    12            42          1.0  absolute_error          1000    0.9766
12    13            42         sqrt   squared_error           100    0.9372
13    14            42         sqrt   squared_error          1000    0.9336
14    15            42         sqrt  absolute_error           100    0.9447
15    16            42         sqrt  absolute_error          1000    0.9298