In [1]:
import pandas as pd
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.drop(columns=["User ID"])
dataset
x=dataset[["Age","EstimatedSalary","Gender_Male"]]
y=dataset[["Purchased"]]
print(y)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/8,random_state=52)
dataset[["Purchased"]].value_counts()
dataset.shape

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

(400, 4)

In [2]:
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0         True
1     35            20000          0         True
2     26            43000          0        False
3     27            57000          0        False
4     19            76000          0         True
..   ...              ...        ...          ...
395   46            41000          1        False
396   51            23000          1         True
397   50            20000          1        False
398   36            33000          0         True
399   49            36000          1        False

[400 rows x 4 columns]

In [3]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, r2_score

pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', KNeighborsClassifier())
])

param_grid = {
    'classifier__n_neighbors': [3, 5, 7, 9, 11, 13, 15, 17, 19, 21],
    'classifier__weights': ['uniform', 'distance'],
    'classifier__metric': ['euclidean', 'manhattan', 'minkowski'],
    'classifier__p': [1, 2]
}

grid = GridSearchCV(
    pipe,
    param_grid,
    cv=5,
    scoring='accuracy',
    refit=True,
    verbose=2,
    n_jobs=-1
)

grid.fit(x_train, y_train.values.ravel())

print("Best Parameters:", grid.best_params_)
print("Best CV Accuracy:", grid.best_score_)

y_pred = grid.best_estimator_.predict(x_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("R_score:", r2_score(y_test, y_pred))

Fitting 5 folds for each of 120 candidates, totalling 600 fits
Best Parameters: {'classifier__metric': 'euclidean', 'classifier__n_neighbors': 13, 'classifier__p': 1, 'classifier__weights': 'uniform'}
Best CV Accuracy: 0.9142857142857143
Test Accuracy: 0.88
R_score: 0.44852941176470584

In [4]:
re=grid.cv_results_ 
grid_predictions = grid.predict(x_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'classifier__metric': 'euclidean', 'classifier__n_neighbors': 13, 'classifier__p': 1, 'classifier__weights': 'uniform'}: 0.44852941176470584

In [5]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_classifier__metric,param_classifier__n_neighbors,param_classifier__p,param_classifier__weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.232368,0.015837,0.040731,0.002797,euclidean,3,1,uniform,"{'classifier__metric': 'euclidean', 'classifie...",0.928571,0.885714,0.914286,0.900000,0.842857,0.894286,0.029416,109
1,0.213137,0.009683,0.039725,0.000855,euclidean,3,1,distance,"{'classifier__metric': 'euclidean', 'classifie...",0.914286,0.871429,0.900000,0.871429,0.871429,0.885714,0.018070,115
2,0.106821,0.106820,0.026965,0.012520,euclidean,3,2,uniform,"{'classifier__metric': 'euclidean', 'classifie...",0.928571,0.885714,0.914286,0.900000,0.842857,0.894286,0.029416,109
3,0.022107,0.000824,0.015102,0.000976,euclidean,3,2,distance,"{'classifier__metric': 'euclidean', 'classifie...",0.914286,0.871429,0.900000,0.871429,0.871429,0.885714,0.018070,115
4,0.022455,0.000393,0.017618,0.000682,euclidean,5,1,uniform,"{'classifier__metric': 'euclidean', 'classifie...",0.928571,0.871429,0.928571,0.928571,0.885714,0.908571,0.024908,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,0.021850,0.001839,0.016892,0.001649,minkowski,19,2,distance,"{'classifier__metric': 'minkowski', 'classifie...",0.900000,0.900000,0.928571,0.942857,0.871429,0.908571,0.024908,22
116,0.025006,0.001016,0.021249,0.001613,minkowski,21,1,uniform,"{'classifier__metric': 'minkowski', 'classifie...",0.885714,0.885714,0.914286,0.928571,0.842857,0.891429,0.029416,112
117,0.023622,0.001534,0.016037,0.001097,minkowski,21,1,distance,"{'classifier__metric': 'minkowski', 'classifie...",0.900000,0.885714,0.928571,0.942857,0.871429,0.905714,0.026496,61
118,0.020746,0.000579,0.017906,0.000825,minkowski,21,2,uniform,"{'classifier__metric': 'minkowski', 'classifie...",0.885714,0.914286,0.928571,0.900000,0.857143,0.897143,0.024578,85
119,0.020830,0.001382,0.014107,0.001012,minkowski,21,2,distance,"{'classifier__metric': 'minkowski', 'classifie...",0.885714,0.900000,0.928571,0.942857,0.871429,0.905714,0.026496,61