In [1]:
import pandas as pd
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.drop(columns=["User ID"])
dataset
x=dataset[["Age","EstimatedSalary","Gender_Male"]]
y=dataset[["Purchased"]]
print(y)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/8,random_state=52)
dataset[["Purchased"]].value_counts()
dataset.shape

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

(400, 4)

In [2]:
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0         True
1     35            20000          0         True
2     26            43000          0        False
3     27            57000          0        False
4     19            76000          0         True
..   ...              ...        ...          ...
395   46            41000          1        False
396   51            23000          1         True
397   50            20000          1        False
398   36            33000          0         True
399   49            36000          1        False

[400 rows x 4 columns]

In [5]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, accuracy_score

pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', LogisticRegression(random_state=0))
])

param_grid = {
    'classifier__C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
    'classifier__solver': ['lbfgs', 'liblinear'],
    'classifier__max_iter': [1000, 2000]
}

grid = GridSearchCV(
    pipe,
    param_grid,
    cv=5,
    scoring='accuracy',
    refit=True,
    verbose=2,
    n_jobs=-1
)

grid.fit(x_train, y_train.values.ravel())

print("Best Parameters:", grid.best_params_)
print("Best CV Accuracy:", grid.best_score_)

y_pred = grid.best_estimator_.predict(x_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("R_score:", r2_score(y_test, y_pred))

Fitting 5 folds for each of 28 candidates, totalling 140 fits
Best Parameters: {'classifier__C': 10, 'classifier__max_iter': 1000, 'classifier__solver': 'lbfgs'}
Best CV Accuracy: 0.8400000000000001
Test Accuracy: 0.88
R_score: 0.44852941176470584

In [6]:
re=grid.cv_results_ 
grid_predictions = grid.predict(x_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'classifier__C': 10, 'classifier__max_iter': 1000, 'classifier__solver': 'lbfgs'}: 0.44852941176470584

In [7]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_classifier__C,param_classifier__max_iter,param_classifier__solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.058823,0.006500,0.025273,0.003202,0.001,1000,lbfgs,"{'classifier__C': 0.001, 'classifier__max_iter...",0.642857,0.642857,0.642857,0.628571,0.628571,0.637143,0.006999,27
1,0.054706,0.002913,0.021002,0.004032,0.001,1000,liblinear,"{'classifier__C': 0.001, 'classifier__max_iter...",0.828571,0.828571,0.885714,0.828571,0.771429,0.828571,0.036140,21
2,0.055959,0.007555,0.014272,0.001451,0.001,2000,lbfgs,"{'classifier__C': 0.001, 'classifier__max_iter...",0.642857,0.642857,0.642857,0.628571,0.628571,0.637143,0.006999,27
3,0.028576,0.001170,0.014092,0.000409,0.001,2000,liblinear,"{'classifier__C': 0.001, 'classifier__max_iter...",0.828571,0.828571,0.885714,0.828571,0.771429,0.828571,0.036140,21
4,0.038074,0.001670,0.014897,0.001732,0.010,1000,lbfgs,"{'classifier__C': 0.01, 'classifier__max_iter'...",0.771429,0.785714,0.771429,0.785714,0.757143,0.774286,0.010690,25
5,0.034833,0.004673,0.018122,0.002664,0.010,1000,liblinear,"{'classifier__C': 0.01, 'classifier__max_iter'...",0.828571,0.842857,0.885714,0.814286,0.785714,0.831429,0.033074,19
6,0.046933,0.002184,0.019345,0.001731,0.010,2000,lbfgs,"{'classifier__C': 0.01, 'classifier__max_iter'...",0.771429,0.785714,0.771429,0.785714,0.757143,0.774286,0.010690,25
7,0.037708,0.001339,0.019580,0.000634,0.010,2000,liblinear,"{'classifier__C': 0.01, 'classifier__max_iter'...",0.828571,0.842857,0.885714,0.814286,0.785714,0.831429,0.033074,19
8,0.049435,0.002566,0.018966,0.001908,0.100,1000,lbfgs,"{'classifier__C': 0.1, 'classifier__max_iter':...",0.800000,0.842857,0.871429,0.814286,0.800000,0.825714,0.027701,23
9,0.041542,0.003572,0.021197,0.002588,0.100,1000,liblinear,"{'classifier__C': 0.1, 'classifier__max_iter':...",0.828571,0.857143,0.885714,0.814286,0.814286,0.840000,0.027701,13
10,0.053585,0.004400,0.022149,0.001099,0.100,2000,lbfgs,"{'classifier__C': 0.1, 'classifier__max_iter':...",0.800000,0.842857,0.871429,0.814286,0.800000,0.825714,0.027701,23
11,0.042528,0.001391,0.021960,0.002109,0.100,2000,liblinear,"{'classifier__C': 0.1, 'classifier__max_iter':...",0.828571,0.857143,0.885714,0.814286,0.814286,0.840000,0.027701,13
12,0.056841,0.007389,0.020572,0.002048,1.000,1000,lbfgs,"{'classifier__C': 1, 'classifier__max_iter': 1...",0.828571,0.857143,0.885714,0.814286,0.800000,0.837143,0.030772,15
13,0.037352,0.005090,0.018567,0.003324,1.000,1000,liblinear,"{'classifier__C': 1, 'classifier__max_iter': 1...",0.828571,0.857143,0.885714,0.814286,0.800000,0.837143,0.030772,15
14,0.051531,0.004967,0.019701,0.002146,1.000,2000,lbfgs,"{'classifier__C': 1, 'classifier__max_iter': 2...",0.828571,0.857143,0.885714,0.814286,0.800000,0.837143,0.030772,15
15,0.041573,0.005630,0.019805,0.002104,1.000,2000,liblinear,"{'classifier__C': 1, 'classifier__max_iter': 2...",0.828571,0.857143,0.885714,0.814286,0.800000,0.837143,0.030772,15
16,0.053843,0.005590,0.021364,0.001698,10.000,1000,lbfgs,"{'classifier__C': 10, 'classifier__max_iter': ...",0.828571,0.857143,0.885714,0.828571,0.800000,0.840000,0.029137,1
17,0.041766,0.004424,0.018980,0.001615,10.000,1000,liblinear,"{'classifier__C': 10, 'classifier__max_iter': ...",0.828571,0.857143,0.885714,0.828571,0.800000,0.840000,0.029137,1
18,0.051172,0.003292,0.017932,0.002713,10.000,2000,lbfgs,"{'classifier__C': 10, 'classifier__max_iter': ...",0.828571,0.857143,0.885714,0.828571,0.800000,0.840000,0.029137,1
19,0.038629,0.002750,0.016309,0.001679,10.000,2000,liblinear,"{'classifier__C': 10, 'classifier__max_iter': ...",0.828571,0.857143,0.885714,0.828571,0.800000,0.840000,0.029137,1
20,0.046803,0.002992,0.019698,0.002091,100.000,1000,lbfgs,"{'classifier__C': 100, 'classifier__max_iter':...",0.828571,0.857143,0.885714,0.828571,0.800000,0.840000,0.029137,1
21,0.040340,0.003647,0.021857,0.001929,100.000,1000,liblinear,"{'classifier__C': 100, 'classifier__max_iter':...",0.828571,0.857143,0.885714,0.828571,0.800000,0.840000,0.029137,1
22,0.060081,0.006036,0.024035,0.002677,100.000,2000,lbfgs,"{'classifier__C': 100, 'classifier__max_iter':...",0.828571,0.857143,0.885714,0.828571,0.800000,0.840000,0.029137,1
23,0.049256,0.005912,0.025821,0.002310,100.000,2000,liblinear,"{'classifier__C': 100, 'classifier__max_iter':...",0.828571,0.857143,0.885714,0.828571,0.800000,0.840000,0.029137,1
24,0.066786,0.006339,0.025394,0.001714,1000.000,1000,lbfgs,"{'classifier__C': 1000, 'classifier__max_iter'...",0.828571,0.857143,0.885714,0.828571,0.800000,0.840000,0.029137,1
25,0.048626,0.007757,0.016277,0.003750,1000.000,1000,liblinear,"{'classifier__C': 1000, 'classifier__max_iter'...",0.828571,0.857143,0.885714,0.828571,0.800000,0.840000,0.029137,1
26,0.040997,0.001994,0.014305,0.001761,1000.000,2000,lbfgs,"{'classifier__C': 1000, 'classifier__max_iter'...",0.828571,0.857143,0.885714,0.828571,0.800000,0.840000,0.029137,1
27,0.029126,0.003191,0.011212,0.000959,1000.000,2000,liblinear,"{'classifier__C': 1000, 'classifier__max_iter'...",0.828571,0.857143,0.885714,0.828571,0.800000,0.840000,0.029137,1